json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
json.loads(frappe.request.data) failed because frappe.request.data was completely empty.
This tells us something fundamental about how Frappe is processing the request. Even though you are sending a perfect JSON body, by the time it gets to our Python script, the frappe.request.data object is empty. This can happen due to an internal request handling mechanism within Frappe.

Since frappe.request.data is empty but frappe.form_dict was also not working as expected, we need a robust script that can handle either scenario. The most reliable way to get the data is to check frappe.request.data first, and if it's empty, fall back to frappe.form_dict.
This will make the script work regardless of how Frappe internally processes the API call.